config_version = "0"

exclude_patterns = [
  "**/*.test.ts",
  "fs_root/",
  "**/e2e.ts",
]

[[source]]
name = "default"
default = true

[smells.boolean_logic]
threshold = 6

[smells.nested_control_flow]
threshold = 3

[smells.return_statements]
enabled = false
